Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2019-11, with the labels that each got.

#254 [JENKINS-59986] Handle broken paths silently
  src/main/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGenerator.java
  src/test/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGeneratorTest.java
Labels: bug

#259 [JENKINS-59985] improve help message of IAR cstat analysis
  src/main/java/io/jenkins/plugins/analysis/warnings/IarCstat.java
Labels: documentation

#262 Bump version of jackson-databind from 2.9.10 to 2.9.10.1
  pom.xml
Labels: dependencies

#263 Fix saving of source code root folders
  pom.xml
  src/main/java/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration.java
Labels: bug

#265 [Axivion Suite] Fix absence type architecture violations may have no source path specified
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/DefaultTransformations.java
  src/test/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionParserTest.java
  src/test/resources/io/jenkins/plugins/analysis/warnings/axivion/av_empty_paths.json
Labels: bug

#267 Add protolint to SUPPORTED-FORMATS.md
  SUPPORTED-FORMATS.md
Labels: documentation

#266 Fix hidden repeatable delete button
  pom.xml
  src/main/java/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration.java
  src/main/java/io/jenkins/plugins/analysis/core/util/GlobalConfigurationItem.java
  src/main/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfiguration.java
  src/main/resources/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/ParserConfiguration/config.jelly
  src/main/resources/issues/repeatable.jelly
Labels: bug

#269 Ensure that IDs are valid URLs
  pom.xml
  src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  src/main/resources/io/jenkins/plugins/analysis/core/util/Messages.properties
  src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java
Labels: enhancement

#274 Add underscores to the allowed set of characters for IDs.
  pom.xml
  src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-id.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-id.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-id.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-id.html
  src/test/java/io/jenkins/plugins/analysis/core/model/LabelProviderFactoryITest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java
Labels: bug

#256 Extract analysis configurations from codingstyle project
  .idea/checkstyle-idea.xml
  bin/clean.sh
  bin/german.sh
  bin/go.sh
  bin/release.sh
  bin/skip.sh
  bin/snapshot.sh
  codacy/checkstyle.xml
  codacy/ruleset.xml
  etc/checkstyle.xml
  etc/ruleset.xml
  etc/ruleset_2_0_0.xsd.xml
  etc/spotbugs-exclusion-filter.xml
  pom.xml
Labels: internal

#275 Improve documentation and describe the ID of the native format parser
  doc/Documentation.md
Labels: documentation

#276 [JENKINS-60263] Do not mark upper case characters as invalid URLs
  src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/help-id.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-id.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-id.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-id.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-id.html
  src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java
Labels: bug
