Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2019-10, with the labels that each got.

#223 Revert PMD version to 6.17.0.
  pom.xml
Labels: dependencies

#226 [JENKINS-58826] Fix visible number of build results in charts
  src/main/java/io/jenkins/plugins/analysis/core/charts/CompositeResult.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/BuildResultStubs.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/CompositeResultTest.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/HealthTrendChartTest.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedTrendChartTest.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/SeverityPieChartTest.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/SeveritySeriesBuilderTest.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChartTest.java
Labels: bug, hacktoberfest

#230 Fix remote API result attribute name in documentation
  doc/Documentation.md
Labels: documentation

#219 [JENKINS-48802] Add configuration of additional source roots (outside of workspace)
  .github/workflows/maven.yml
  .travis.yml
  README.md
  doc/Documentation.md
  doc/images/affected-files.png
  doc/images/encoding.png
  doc/images/source-directories-white-list.png
  pom.xml
  src/main/java/io/jenkins/plugins/analysis/core/model/ReportLocations.java
  src/main/java/io/jenkins/plugins/analysis/core/model/SourceDirectory.java
  src/main/java/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep.java
  src/main/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGenerator.java
  src/main/java/io/jenkins/plugins/analysis/core/util/AffectedFilesResolver.java
  src/main/java/io/jenkins/plugins/analysis/core/util/GlobalConfigurationFacade.java
  src/main/java/io/jenkins/plugins/analysis/core/util/GlobalConfigurationItem.java
  src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  src/main/java/io/jenkins/plugins/analysis/core/util/SourceDirectoryResolver.java
  src/main/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfiguration.java
  src/main/resources/io/jenkins/plugins/analysis/core/model/SourceDirectory/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration/config.properties
  src/main/resources/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration/help-sourceDirectories.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-sourceDirectory.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-sourceDirectory.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-sourceDirectory.html
  src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-sourceDirectory.html
  src/main/resources/issues/advanced-step-warning.jelly
  src/main/resources/issues/scan-parameters.jelly
  src/main/resources/issues/scan-parameters.properties
  src/test/java/io/jenkins/plugins/analysis/core/model/ReportLocationsTest.java
  src/test/java/io/jenkins/plugins/analysis/core/model/WarningsPluginConfigurationTest.java
  src/test/java/io/jenkins/plugins/analysis/core/scm/GitBlamerITest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGeneratorITest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGeneratorTest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/AffectedFilesResolverTest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/SourceDirectoryResolverTest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/ConfigurationAsCodeITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/DumbSlaveITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfigurationTest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/AffectedFilesResolverITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/RecorderConfigurationITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/BlamesTable.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/FreestyleConfiguration.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/IssueRow.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/PageObject.java
  src/test/resources/io/jenkins/plugins/analysis/core/util/child/child.txt
  src/test/resources/io/jenkins/plugins/analysis/warnings/sourceDirectories.yaml
Labels: enhancement

#239 Cleanup some warnings and TODOs.
  Jenkinsfile
  src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  src/main/java/io/jenkins/plugins/analysis/core/util/GlobalConfigurationItem.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChartTest.java
  src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnTest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGeneratorITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/AffectedFilesResolverITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/MavenIssuesRecorderITest.java
Labels: internal

#242 Improve performance of Axivion Suite
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxIssueKind.java
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxRawIssue.java
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionDashboard.java
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionParser.java
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/DefaultTransformations.java
  src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
  src/main/resources/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite/config.properties
  src/test/java/io/jenkins/plugins/analysis/warnings/axivion/TestDashboard.java
Labels: enhancement
