Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2019-09, with the labels that each got.

#185 [JENKINS-57673][JENKINS-56570] Improve layout of fixed warnings view
  .idea/.gitignore
  src/main/java/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail.java
  src/main/java/io/jenkins/plugins/analysis/core/model/IssuesDetail.java
  src/main/resources/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail/index.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/model/Messages.properties
  src/main/resources/issues/sourceLink.jelly
  src/main/webapp/js/fixed-detail.js
  src/main/webapp/js/issues-detail.js
  src/test/java/io/jenkins/plugins/analysis/core/model/FixedWarningsDetailTest.java
Labels: enhancement

#182 Generalize table row models
  src/test/java/io/jenkins/plugins/analysis/core/scm/GitBlamerITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/AffectedFilesResolverITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/MiscIssuesRecorderITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/BlamesRow.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/IssueRow.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/TableRow.java
Labels: internal, tests

#188 Add support for PVS-Studio
  SUPPORTED-FORMATS.md
  src/main/java/io/jenkins/plugins/analysis/warnings/PVSStudio.java
  src/main/webapp/icons/LICENSE.txt
  src/main/webapp/icons/pvs-24x24.png
  src/main/webapp/icons/pvs-48x48.png
  src/test/java/io/jenkins/plugins/analysis/warnings/ParsersITest.java
  src/test/resources/io/jenkins/plugins/analysis/warnings/TestReport.plog
Labels: enhancement

#195 [JENKINS-59178] Fix NPE when aggregating different results in matrix build
  src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesAggregator.java
  src/test/java/io/jenkins/plugins/analysis/core/steps/IssuesAggregatorTest.java
Labels: bug

#197 Remove git-forensics dependency, add it as integration test dependency
  pom.xml
Labels: bug

#198 [JENKINS-59118] Add a test that shows that files are correctly parsed
  pom.xml
  src/test/java/io/jenkins/plugins/analysis/warnings/StepsITest.java
  src/test/resources/io/jenkins/plugins/analysis/warnings/issue59118.txt
Labels: tests

#200 [JENKINS-58635] Do not fail quality gate for the first build
  src/main/java/io/jenkins/plugins/analysis/core/model/DeltaReport.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/QualityGateITest.java
Labels: bug

#184 [JENKINS-58824] Add test for wrong case for paths in MSBuild (on Windows)
  src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGeneratorITest.java
Labels: tests

#201 [JENKINS-56264] Use build numbers in URLs, not display name
  src/main/java/io/jenkins/plugins/analysis/core/charts/HealthTrendChart.java
  src/main/java/io/jenkins/plugins/analysis/core/charts/LinesChartModel.java
  src/main/java/io/jenkins/plugins/analysis/core/charts/LinesDataSet.java
  src/main/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedTrendChart.java
  src/main/java/io/jenkins/plugins/analysis/core/charts/SeriesBuilder.java
  src/main/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChart.java
  src/main/java/io/jenkins/plugins/analysis/core/charts/ToolsTrendChart.java
  src/main/webapp/js/simple-trend-chart.js
  src/test/java/io/jenkins/plugins/analysis/core/charts/LinesChartModelTest.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/LinesDataSetTest.java
  src/test/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChartTest.java
Labels: bug

#203 [Jenkins 58420] Do not use JobAction to obtain build results.
  src/main/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn.java
  src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
  src/main/java/io/jenkins/plugins/analysis/core/model/ToolSelection.java
  src/main/java/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet.java
  src/main/java/io/jenkins/plugins/analysis/core/portlets/IssuesTablePortlet.java
  src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnITest.java
  src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnTest.java
  src/test/java/io/jenkins/plugins/analysis/core/portlets/IssuesTablePortletITest.java
  src/test/java/io/jenkins/plugins/analysis/core/portlets/IssuesTablePortletTest.java
  src/test/java/io/jenkins/plugins/analysis/core/testutil/JobStubs.java
  src/test/resources/io/jenkins/plugins/analysis/core/portlets/checkstyle-filtering.xml
  src/test/resources/io/jenkins/plugins/analysis/core/portlets/checkstyle-healthReport.xml
  src/test/resources/io/jenkins/plugins/analysis/core/portlets/eclipse.txt
Labels: bug

#208 [JENKINS-57857] Add a unique ID to the chart divs.
  src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/portlet.jelly
Labels: bug

#209 Fix pattern for PVS
  SUPPORTED-FORMATS.md
  src/main/java/io/jenkins/plugins/analysis/warnings/PVSStudio.java
Labels: bug

#210 Typo in commandline
  doc/Documentation.md
Labels: documentation

#202 Activate ESLint and apply common style for all JS files
  .eslintrc.yml
  package-lock.json
  package.json
  src/main/webapp/js/fixed-detail.js
  src/main/webapp/js/issues-detail.js
  src/main/webapp/js/no-prototype.js
  src/main/webapp/js/pie-chart.js
  src/main/webapp/js/simple-trend-chart.js
  src/main/webapp/js/source-detail.js
  src/main/webapp/js/trend-chart.js
  src/test/resources/io/jenkins/plugins/analysis/warnings/job-dsl-warnings-ng.yaml
Labels: internal

#211 [JENKINS-58383] [JENKINS-57377] Add configuration of aggregation chart
  clean.sh
  go.sh
  skip.sh
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
  src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  src/main/java/io/jenkins/plugins/analysis/core/util/AggregationTrendChartDisplay.java
  src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/config.properties
  src/main/resources/io/jenkins/plugins/analysis/core/util/Messages.properties
  src/main/resources/issues/help-aggregationTrend.html
  src/main/resources/issues/recorder.jelly
  src/main/resources/issues/recorder.properties
  src/main/webapp/js/simple-trend-chart.js
  src/main/webapp/js/trend-chart.js
  src/test/java/io/jenkins/plugins/analysis/warnings/ConfigurationAsCodeITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/JobActionITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/JobDslITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/RecorderConfigurationITest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/FreestyleConfiguration.java
  src/test/resources/io/jenkins/plugins/analysis/warnings/job-dsl-checkstyle.yaml
  src/test/resources/io/jenkins/plugins/analysis/warnings/job-dsl-cpd.yaml
  src/test/resources/io/jenkins/plugins/analysis/warnings/job-dsl-pmd.yaml
  src/test/resources/io/jenkins/plugins/analysis/warnings/job-dsl-warnings-ng.yaml
Labels: enhancement

#217 [JENKINS-57312] Add a type configuration to columns and tokens
  clean.sh
  doc/Documentation.md
  doc/images/chart-portlet.png
  doc/images/column.png
  src/main/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn.java
  src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
  src/main/java/io/jenkins/plugins/analysis/core/model/DeltaReport.java
  src/main/java/io/jenkins/plugins/analysis/core/tokens/IssuesSizeTokenMacro.java
  src/main/java/io/jenkins/plugins/analysis/core/util/IssuesStatistics.java
  src/main/java/io/jenkins/plugins/analysis/core/util/IssuesStatisticsBuilder.java
  src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  src/main/java/io/jenkins/plugins/analysis/core/util/QualityGate.java
  src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/config.jelly
  src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/config.properties
  src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/help-type.html
  src/main/resources/io/jenkins/plugins/analysis/core/util/Messages.properties
  src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnITest.java
  src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnTest.java
  src/test/java/io/jenkins/plugins/analysis/core/model/AnalysisResultTest.java
  src/test/java/io/jenkins/plugins/analysis/core/model/DeltaReportTest.java
  src/test/java/io/jenkins/plugins/analysis/core/portlets/IssuesTablePortletTest.java
  src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
  src/test/java/io/jenkins/plugins/analysis/core/testutil/JobStubs.java
  src/test/java/io/jenkins/plugins/analysis/core/tokens/IssuesSizeTokenMacroTest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/IssuesStatisticsTest.java
  src/test/java/io/jenkins/plugins/analysis/core/util/QualityGateEvaluatorTest.java
  src/test/java/io/jenkins/plugins/analysis/warnings/recorder/TokenMacroITest.java
  src/test/resources/design.puml
  src/test/resources/io/jenkins/plugins/analysis/core/model/result.xml
Labels: enhancement

#220 Bump version of jackson-databind to 2.9.10
  pom.xml
Labels: dependencies
