Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2020-04, with the labels that each got.

#435 Add test case that tries to expose JENKINS-61593
  Jenkinsfile
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/Sanitizer.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/recorder/TokenMacroITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/all-severities.xml
Labels: tests

#439 [JENKINS-56699] Replace newlines `\n` with HTML equivalent `<br>` tags
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SourcePrinter.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/SourcePrinterTest.java
Labels: bug

#451 Replace jackson-databind with jackson2-api plugin
  plugin/pom.xml
Labels: dependencies
