Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2020-03, with the labels that each got.

#415 [JENKINS-61293] Expose NPE during unmarshalling
  pom.xml
  src/test/java/io/jenkins/plugins/analysis/core/model/ReportXmlStreamTest.java
  src/test/resources/io/jenkins/plugins/analysis/core/model/npe.xml
Labels: bug, tests

#414 [JENKINS-59592] Link issue column to selected type
  src/main/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn.java
  src/main/java/io/jenkins/plugins/analysis/core/util/IssuesStatistics.java
  src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnTest.java
  src/test/java/io/jenkins/plugins/analysis/core/testutil/JobStubs.java
Labels: enhancement

#434 Update token macro documentation
  doc/Documentation.md
Labels: documentation
