Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2020-12, with the labels that each got.

#701 Added OT-Dockerlinter integration
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/OTDockerLint.java
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/Messages.properties
  plugin/src/main/webapp/icons/LICENSE.txt
  plugin/src/main/webapp/icons/ot-docker-linter-24x24.png
  plugin/src/main/webapp/icons/ot-docker-linter-48x48.png
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/ot-docker-linter.json
Labels: feature

#712 Improve checkbox names
  SUPPORTED-FORMATS.md
  doc/Documentation.md
  doc/images/forensics-view.png
  doc/images/reference-step.png
  doc/images/reference-warnings.png
  doc/images/reference.png
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.properties
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/config.properties
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesTablePortlet/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesTablePortlet/config.properties
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/FindBugs/local-config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/FindBugs/local-config.properties
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/SpotBugs/local-config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/SpotBugs/local-config.properties
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks/config.properties
  plugin/src/main/resources/issues/publish-parameters.jelly
  plugin/src/main/resources/issues/publish-parameters.properties
  plugin/src/main/resources/issues/recorder.jelly
  plugin/src/main/resources/issues/recorder.properties
  plugin/src/main/resources/issues/scan-parameters.jelly
  plugin/src/main/resources/issues/scan-parameters.properties
Labels: enhancement

#719 Also check for permissions in `check` methods
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/IncludeType.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/RegexpFilter.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ToolSelection.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/filter/RegexpFilterTest.java
Labels: bug

#724 Improve layout of checks markup
  doc/Documentation.md
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
  plugin/src/main/resources/issues/publish-parameters.jelly
  plugin/src/main/resources/issues/publish-parameters.properties
  plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
  ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesRecorder.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/FreeStyleConfigurationUITest.java
Labels: enhancement
