Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2021-02, with the labels that each got.

#767 [JENKINS-63782] Ignore case when comparing paths on Windows
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/AffectedFilesResolver.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/AffectedFilesResolverTest.java
Labels: bug

#766 [JENKINS-64051] Do not reformat punctuation when building the description
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DetailsTableModelTest.java
Labels: bug

#780 [JENKINS-63109] Add a return value for the step `recordIssues`
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/StaticAnalysisRun.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java
Labels: enhancement

#781 [JENKINS-63010] Catch `InvalidPathException` and report error.
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
Labels: bug

#782 [JENKINS-62415] Print parameters of step in Pipeline Steps View (flowGraphTable)
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptorTest.java
Labels: enhancement

#787 [JENKINS-61834] Add a raw name for the results to be used as display name
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/JobActionTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProviderTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/SanitizerTest.java
Labels: bug

#765 [JENKINS-64376] add issue description as hidden column for search
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/BlamesModel.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ForensicsModel.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesModel.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/BlamesModelTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ForensicsModelTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/IssuesModelTest.java
Labels: enhancement

#790 [JENKINS-61196] Add an additional trend chart option to show only the aggregation
  doc/Documentation.md
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/TrendChartType.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/JobActionITest.java
Labels: enhancement

#785 [JENKINS-64657] Use new DoxygenParser for Doxygen
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/Doxygen.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
Labels: bug

#800 [JENKINS-64830] Add `AGGREGATION_ONLY` option in UI
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-trendChartType.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-trendChartType.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-trendChartType.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-trendChartType.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/util/Messages.properties
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PyLintTest.java
Labels: bug

#801 [JENKINS-64627] Use CONFIGURE permission of specific job if possible
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/RegexpFilter.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ToolSelection.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/QualityGate.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/DuplicateCodeScanner.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/filter/RegexpFilterTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ToolSelectionDescriptorTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/QualityGateTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java
Labels: bug

#807 Dependabot/maven/io.jenkins.plugins forensics api 0.10.1
  bin/release.sh
  plugin/pom.xml
Labels: internal

#830 Fix permissions for Groovy parser selection
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyScript.java
Labels: bug

#821 [JENKINS-62963] Bump version of analysis-pom to to 5.0.0
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/SeverityPalette.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportXmlStream.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SourcePrinter.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/IssuesStatistics.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/LocalizedSeverity.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/PmdMessages.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/PyLint.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/DefaultTransformations.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfiguration.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DeltaReportTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/PropertyStatisticsTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ReportXmlStreamTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisToolSuiteTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/MatrixBridgeTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/DynamicDocumentParserTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/AffectedFilesResolverITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/DryITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/MiscIssuesRecorderITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsOnAgentITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerBenchmark.java
  ui-tests/pom.xml
  ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesColumnConfiguration.java
  ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesDetailsTable.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/IssuesColumnUiTest.java
Labels: internal
