Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2021-01, with the labels that each got.

#725 [JENKINS-62416] Add column for new warnings in properties table
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesDetail.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/PropertyStatistics.java
  plugin/src/main/resources/issues/property.jelly
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/PropertyStatisticsTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/pageobj/PropertyTable.java
  ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisResult.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java
Labels: enhancement

#740 [JENKINS-64622] - Gracefully handles patterns that contain optional groups
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScanner.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerTest.java
Labels: bug

#741 Add missing newline after GitHub checks details table
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
Labels: bug

#747 Select blamer for a specific SCM
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep.java
  plugin/src/main/resources/issues/scan-parameters.jelly
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ReferenceFinderITest.java
  ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesRecorder.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/FreeStyleConfigurationUiTest.java
Labels: enhancement

#750 Pass SCM selection to repository miner
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/GitForensicsITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/PackageDetectorsITest.java
Labels: bug, tests

#753 Add documentation for filters
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-filters.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-id.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-filters.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-id.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-filters.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-id.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-filters.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-id.html
Labels: documentation

#754 [JENKINS-61484] tooltip will not cover link when placed right
  plugin/src/main/resources/issues/property.jelly
Labels: bug

#759 [JENKINS-56594] - Hide empty trend charts
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/JobAction/floatingBox.jelly
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/JobActionTest.java
Labels: enhancement

#763 Show validation error message if parser is not valid
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser/config.jelly
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParserTest.java
Labels: enhancement
