Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2022-08, with the labels that each got.

#1332 Pick up `forkCount` fix from `acceptance-test-harness`
  ui-tests/pom.xml
Labels: dependencies, java

#1334 Add `pluginRepositories` for PCT
  pom.xml
  ui-tests/pom.xml
Labels: internal

#1333 Let CI run with JDK 11 and 17
  .github/workflows/ci.yml
  plugin/pom.xml
  ui-tests/pom.xml
Labels: internal

#1340 Use new theme-aware carousel component of BS plugin
  plugin/pom.xml
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/filled.jelly
  plugin/src/main/resources/issues/history.jelly
  ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisResult.java
Labels: enhancement

#1206 Use new Jenkins table styling for tooltips
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/column.jelly
Labels: enhancement

#1342 Use new Jenkins styles for Boostrap tabs
  plugin/pom.xml
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/filled.jelly
  plugin/src/main/resources/issues/property-tab.jelly
  plugin/src/main/resources/issues/property.jelly
Labels: enhancement

#1345 Fix saving of active tab in browser local storage
  plugin/src/main/webapp/js/issues-detail.js
Labels: bug

#1339 Make AncestorInPath Object include Multibranch pipelines
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
Labels: bug
