Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2023-03, with the labels that each got.

#1462 Allow plugin to be included in BOM
  plugin/pom.xml
Labels: tests

#1434 Move baseline to Java 11
  README.md
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailFactory.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/FilesScanner.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/InfoErrorDetail.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/PropertyStatistics.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SourceDetail.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SourcePrinter.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Summary.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ToolSelection.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisExecution.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesAggregator.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/LogHandler.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/PipelineResultHandler.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/QualityGate.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/RunResultHandler.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/Sanitizer.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/StageResultHandler.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/Thresholds.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfiguration.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/AgentScanner.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/filter/RegexpFilter/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ToolSelection/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyScript/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks/config.jelly
  plugin/src/main/resources/issues/tool-defaults.jelly
  plugin/src/main/resources/parser/advanced.jelly
  plugin/src/main/webapp/css/custom-style.css
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/InfoErrorDetailTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/PropertyStatisticsTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/SourcePrinterTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/LogHandlerTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/SanitizerTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/util/StageResultHandlerTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PackageArchitectureTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParserTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/QualityGateITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java
Labels: removed

#1472 Remove and metrics-aggregation tests
  plugin/pom.xml
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/AutogradingPluginITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/MetricsAggregationPluginITest.java
Labels: tests

#1478 Do not use format method when simply copying log messages
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
Labels: bug

#1469 Include Parser for Code Generartor Tool
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/CodeGenerator.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/CodeGenerator.log
Labels: enhancement

#1495 Get versions of dependencies from BOM
  plugin/pom.xml
Labels: internal

#1496 Add SCM section to `pom.xml`
  pom.xml
Labels: internal

#1500 Remove dot from checks title
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
Labels: enhancement
