Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2024-01, with the labels that each got.

#1648 [JENKINS-71435] Make empty properties clickable
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DetailsTableModelTest.java
Labels: enhancement

#786 Add an integration test for the parser of the parasoft-findings plugin
  plugin/pom.xml
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/parasoft.xml
Labels: tests

#1656 [JENKINS-71492] Limit property `skipPostProcessing` to package and module detection.
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
  plugin/src/main/resources/issues/scan-parameters.properties
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ModuleDetectorITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/PackageDetectorsITest.java
Labels: enhancement

#1661 Use success colour variable rather than hardcoded colour
  plugin/src/main/webapp/css/custom-style.css
  plugin/src/main/webapp/css/pull-request-portlet.css
Labels: bug

#1659 [JENKINS-65845] Don't link to deleted builds
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesDetail.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/AbstractDetailsModelTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProviderTest.java
Labels: bug
