Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2024-09, with the labels that each got.

#1814 [JENKINS-72973] Add an option to skip the SCM delta calculation
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-skipDeltaCalculation.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-skipDeltaCalculation.html
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-skipDeltaCalculation.html
  plugin/src/main/resources/issues/publish-parameters.jelly
  plugin/src/main/resources/issues/publish-parameters.properties
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/GitForensicsITest.java
Labels: enhancement

#1824 Adding Yocto Scanner support.
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/YoctoScanner.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/yocto_scanner_result.json
Labels: feature

#1834 Use new Jenkins baseline 2.462
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyExpressionMatcher.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/TimeStamperPluginITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/TokenMacroITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/QualityGateITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsOnAgentITest.java
  ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AbstractIssuesTable.java
Labels: bug

#1837 Test with job-dsl and maven plugin versions from BOM
  plugin/pom.xml
Labels: dependencies

#1839 Remove unused exclusion of spotbugs-annotations from checks-api
  plugin/pom.xml
Labels: dependencies
