Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2024-02, with the labels that each got.

#1671 Make the no-issues icon green again
  plugin/src/main/webapp/css/custom-style.css
Labels: bug

#1686 Update custom plugin code example
  doc/Custom-Plugin.md
Labels: documentation

#1691 Fix warnings
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AggregationAction.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/util/WarningsQualityGateEvaluator.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/CodeGenerator.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/CrossCoreEmbeddedStudio.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/EmbeddedEngineer.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/OwaspDependencyCheck.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RfLint.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/SimulinkCheck.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/DynamicDocumentParser.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/TabLabelProviderTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuiteSerializationTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuiteTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyScriptITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfigurationITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfigurationTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerBenchmark.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java
Labels: internal

#1690 Use the correct property name `skipBlames`
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep.java
Labels: bug

#1694 [JENKINS-72493] Use json-path-api plugin
  plugin/pom.xml
Labels: internal

#1695 Fix `LineRange` serialization alias
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportXmlStream.java
Labels: bug
