Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2024-04, with the labels that each got.

#1727 Restore ability of `publishIssues` to run without a workspace
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/PublishIssuesStepITest.java
Labels: bug

#1716 Test on Java 21
  Jenkinsfile
Labels: tests

#1728 Use ASM API plugin as dependency
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
Labels: dependencies

#1733 Use the new square SVG image for PMD results
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/Pmd.java
  plugin/src/main/webapp/icons/pmd-24x24.png
  plugin/src/main/webapp/icons/pmd-48x48.png
  plugin/src/main/webapp/icons/pmd.svg
Labels: enhancement
