Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2024-12, with the labels that each got.

#1912 Replace YUI button class with Jenkins default button class for reset reference build action
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly
Labels: internal

#1897 Add missing `scm` property in configuration screen
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/config.jelly
Labels: bug

#1909 Adding Valgrind Issues reporting
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/Valgrind.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/valgrind.xml
Labels: enhancement
