Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2024-10, with the labels that each got.

#1856 Correct CLI argument hint for PHPStan
  SUPPORTED-FORMATS.md
Labels: documentation

#1859 [JENKINS-73894] Un-inline JavaScript in IssuesChartPortlet/portlet.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/portlet.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/render-trend-chart.js
Labels: internal

#1851 Use the parser category to assign different action icons
  .github/workflows/ci.yml
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisModelParser.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/ErrorProne.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/OwaspDependencyCheck.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RegisteredParser.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/YoctoScanner.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/FiltersITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/MiscIssuesRecorderITest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/core/steps/pmd-report.xml
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/integrations/pmd-report.xml
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/module-filter/pmd-report.xml
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/DashboardViewPortletUiTest.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/DetailsTabUiTest.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/IssuesColumnUiTest.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java
  ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/WarningsPluginUiTest.java
  ui-tests/src/test/resources/aggregation/pmd-report.xml
  ui-tests/src/test/resources/build_status_test/build_01/checkstyle-report.xml
  ui-tests/src/test/resources/build_status_test/build_01/pmd-report.xml
  ui-tests/src/test/resources/build_status_test/build_02/checkstyle-report.xml
  ui-tests/src/test/resources/build_status_test/build_02/pmd-report.xml
  ui-tests/src/test/resources/checkstyle-report.xml
  ui-tests/src/test/resources/dashboard_test/checkstyle-report.xml
  ui-tests/src/test/resources/dashboard_test/pmd-report.xml
  ui-tests/src/test/resources/issue_filter/checkstyle-report.xml
  ui-tests/src/test/resources/message_box/checkstyle-report.xml
Labels: enhancement

#1862 [JENKINS-73896] Un-inline JavaScript in ResultAction/summary.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/bind-reset-button.js
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly
Labels: internal
