Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2025-02, with the labels that each got.

#1918 [JENKINS-72777] Use icon of configured parser even when ID is overwritten by the user
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DeltaReport.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IconLabelProvider.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/LabelProviderFactory.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SvgIconLabelProvider.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/IconLabelProviderTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/testutil/WarningsIntegrationTest.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/MiscIssuesRecorderITest.java
Labels: bug

#1937 Migrate from EE 8 to EE 9
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesDetail.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
  plugin/src/test/java/io/jenkins/plugins/analysis/core/model/JobActionTest.java
Labels: internal

#1946 Depends on jsoup API plugin
  plugin/pom.xml
Labels: dependencies

#1955 Add methods to configure context lines for fingerprinting
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
  plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.properties
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/help-linesLookAhead.html
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/AffectedFilesResolverITest.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/FingerprintTestWithModification.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/FingerprintTestWithoutModification.java
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/javalog-1.txt
  plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/javalog-2.txt
Labels: enhancement

#1901 Recognize `\R` for multiline regex in groovy parsers
  plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
  plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParserTest.java
Labels: enhancement
