Repository jenkinsci/warnings-ng-plugin, pull requests merged in 2025-07, with the labels that each got.

#1773 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: tests

#2067 Replace Bootstrap cards with Design Library cards
  .gitignore
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/empty.jelly
  plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/filled.jelly
  plugin/src/main/resources/issues/history.jelly
  plugin/src/main/resources/issues/log-messages.jelly
  plugin/src/main/resources/issues/zero-issues.jelly
  plugin/src/main/webapp/css/custom-style.css
Labels: enhancement

#2072 Expand information messages card
  plugin/src/main/resources/issues/log-messages.jelly
  plugin/src/main/webapp/css/custom-style.css
Labels: enhancement

#2073 [JENKINS-75935][JENKINS-75748] Remove duplicate transient actions
  plugin/src/main/java/io/jenkins/plugins/analysis/core/model/MissingResultFallbackHandler.java
Labels: bug
